name: Sync Data

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: "sync"
  cancel-in-progress: false

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_TOKEN: ${{ secrets.DATABASE_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: bun install

    - name: "Sync data: YouTube"
      run: bun run sync-data:youtube
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    - name: "Sync data: Wikipedia"
      run: bun run sync-data:wikipedia

    - name: "Revalidate website"
      run: bun run sync-data:revalidate
      env:
        REVALIDATE_URL: ${{ secrets.REVALIDATE_URL }}
        REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}